{% set name = "pyodeint" %}
{% set version = "0.10.6" %}
{% set sha256 = "0b6a04865b55f35bb57cdce41a20d538ae6cd92cd6812869dac52fe8ff3f9782" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and not py>=35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - numpy
    - libboost-headers
    - pip
  run:
    - python

test:
  imports:
    - pyodeint
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs pyodeint

about:
  home: https://github.com/bjodah/pyodeint
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python wrapper around odeint (from the boost C++ library)
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
