{% set name = "pyodeint" %}
{% set version = "0.10.5" %}
{% set sha256 = "d881285583879a7fd51492bcd11b86f460821d5e6b5fd935f6b5891b50cb9d77" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and not py>=35]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - cython
    - setuptools
    - numpy
    - libboost-headers
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyodeint
  requires:
    - pytest
  commands:
    - python -m pytest --pyargs pyodeint

about:
  home: https://github.com/bjodah/pyodeint
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Python wrapper around odeint (from the boost C++ library)
  doc_url: https://bjodah.github.io/{{ name }}/latest

extra:
  recipe-maintainers:
    - bjodah
