travis:
  secure:
    BINSTAR_TOKEN: lkRBwK6ePG1+KQQ1agcFk98TLgg8uq9k6ZlGnA8PLDBYEfKGmgdSqD6p5CslIOYTl9R9X8VcTeopEhPKZp9hZG+7J1hflLrjVm90ImIOmOEVDg7DmXnBlqCqMquVht09+in3fpJ9Ra3wjdqCfQdeheIstf5SL2nSW5YhZIg3r87dZapC+YRSGaYogsjAubDqbEIwJODICm0qCLJyL+eBOC1PbRsJsFgp+4vjCiXSTY9JWWbJz6wjWLzEqKXUPRcmTCW4iNXjkj7zL8rKG8cNinoHkyuVr1BjA9Q/ck1lemXKzDyGTmVTTMXSBc4IQKf0NlUgBHjgLFHt1HSdnASHm5kcmuopH+ALC4EaLShBhSNd7ObcwnPqbhPLJXliVmRUVe9vMivZ5JBDWW90Lvm2E601ZjcN64N+RHAfZ79y+1sigQNZOSI+1KJWgPg0h+1x3UdBnK3YsyeV/GyzXuxHh3fpFNhKa55fJHvDy0RyFacWVny8TFG3Za5DZNDUGCXUzyFx5cVfE2vztnBX2NmGHX3+QO98XA9NuPocZ7juIyzClOu+tVf4fd+ezCLhQeL72ur3jdAsCMWgFYziMbHRKV94ou3GnZA9Bwto77+NPjjmwGnXze5ZLaAZYiolxsK1D4gIJ6j7Sy5e241VjAeW2pldsOIWQVW1UUGeEQCO92g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
