appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: AcISXiuLXVfj1dVBVHoNp/dccdaquPPm+KsT6uGO5yvfah8riG49LXTjl0ssIolL/5QBxC/KlIlxbz9vYnHCK5z28v0auCUO6iLJKCkC6dfgvNH/N7qQrDSVb3jbaHSJZfj5jgpuQR+bGnJc0mXJxOIDSMUWop/hI3JzVaL63zR9w8WRyVgvwgboY8css2uwWu2M1edfDLi4KQ2p//vCtRBvk3Vm9+Ev6qj+YUymBs6/s1SkcneYOGmUp5Ca81isGHVo0R+RbvYJrkuLBvmIpfKZopEl0kOWpyZpEEK5IhI3nKa+xggofEiMrqwSEqykiaztzFghsW9ia44k+NgCOmO+V3dVzJyqyjNBlUXEuE37dDCB+M8zzOxivBN7akocoijPwNYLuBs7XqLby1RhHCEj3h2QpQCJla5pNp9TdhlqTtIcanM9YLkm/IQAEgQu7U/GJ40GXnrltubAWcJQCzUTob7TpUzQas9xDFsCB1WTzEf7PKCD5xI9mRf7drFh6fbKlvv459Y7SQi+VoiDrD2p4ba5lijyLj8gOnsM1i8JgWGMtEfvwV+7Fet56fk9w3nRvAEmCG23Z2PusbkyrBkIVbVstEUfC9IuHDayx3FYokdhOCYnHwo/BTHs9TOWHiBy57lhxcws2svtKYAUUob7yIfd8vuNXVZHMV7VmVk=}
provider:
  win: azure
conda_forge_output_validation: true
